Metrics/AbcSize:
  Max: 24

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
